import '../app/globals.css';
import Navbar from '../app/components/Navbar/index';
import Footer from '../app/components/Footer/index';

import Banner from '../app/components/Banner/index';
import Wework from '../app/components/Wework/index';
import FAQ from '../app/components/FAQ/index';
import Testimonials from '../app/components/Testimonials/index';
import Articles from '../app/components/Articles/index';
import Insta from '../app/components/Insta/index';


export const metadata = {
    title: 'nzmcr',
    description: 'Generated by create next app',
  }
  
export default function Home() {
    return (
      <main>
        <Navbar />
        <Testimonials />
      </main>
    )
  }
  